/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:a2b29012-5903-48bd-93bd-6007467c5e31",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_IHtlLQhAJ",
    "aws_user_pools_web_client_id": "45u8jn02elq8151qso7e8qtun1",
    "oauth": {}
};


export default awsmobile;
